version: '3'
services:
  mockserver:
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json
      - MOCKSERVER_CORS_ALLOW_HEADERS=Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary, Authorization
      - MOCKSERVER_CORS_ALLOW_METHODS=CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, PATCH, TRACE
      - MOCKSERVER_CORS_ALLOW_ORIGIN=*
      - MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES=true
    image: mockserver/mockserver
    ports:
      - 1080:1080
    volumes:
      - ${PWD}/initializerJson.json:/config/initializerJson.json
  rails:
    build: .
    depends_on:
      - mockserver
    environment:
      - RAILS_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/hellorails:/app
